### ISSUE TITLE
Missing branch/packages for 1.5.4 release

### ISSUE THREAD

**Issue by dahorak** [Tendrl/tendrl-selinux#3] opened 2017-11-06 15:38 UTC
There seems to be no branch and thus no packages for 1.5.4 release.

**Comment by cybernth** [comment] 2017-11-06 15:48
@dahorak , There are no changes to selinux and hence the branches are not created

**Comment by dahorak** [comment] 2017-11-07 07:51
@nthomas-redhat I'm not sure if there is some official guideline about this, but my personal opinion is, that it would be better to rebuild it too (even without any changes).
Otherwise it will be very confusing, if you will have all packages in some specific version and one in older version. It would be difficult to find out, if you have all the packages up to date.

**Comment by r0h4n** [comment] 2017-11-10 05:36
@dahorak This is not a bug, wontfix.  If there are new source code changes, we can do a build

**Closed as completed by r0h4n** 2017-11-10 05:36 UTC
